export enum StockCollections {
    IPhone11 = 'IPH11',
    IPhone11Pro = 'IPH11P',
    IPhone11ProMax = 'IPH11PM',
    IPhone12 = 'IPH12',
    IPhone12Mini = 'IPH12M',
    IPhone12ProMax = 'IPH12PM',
    IPhoneXS = 'IPHXS',
    IPhoneXSMax = 'IPHXSM',
    IPhoneXR = 'IPHXR',
    IPhone13 = 'IPH13',
    IPhone13Pro = 'IPH13P',
    IPhone13ProMax = 'IPH13PM',
    IPhone13Mini = 'IPH13M',
    IPhoneSE = 'IPHSE',
    IPhone8plus = 'IPH8P',
    AirpodsPro = 'AIRP',
    Airpods1era = 'AIR',
    Airpods3era = 'AIR3',
    Cable = 'CABLE',
    Mica = 'MICA',
    Camara = 'CAMARA',
    Gift = 'GIFT',
    Watch = 'WATCH',
    Popsocket = 'Popsocket'
}
